### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by ashprakasan** [ashprakasan/TusharBirthday#1]
# Tushar's birthday is coming up! 🥳🍾

It's time to take a break and join us for an evening of dinner 🥘, drinks 🥂, music 🎸 and laughter 😆. 
Get dressed 🕺 and take a cab 🚗 to a party that is *NOT* virtual.

### Command

```
party init --loud
```

### When

`Saturday, 30-Jan-21 19:30:00 UTC+05:30 🌘`

### Where 

```
2904, Elisium (Tower 6), B-Wing, 
Lodha New Cuffe Parade, 
Mumbai 🏠
```

### Steps

1. We'd love it if you bring a date. 👠👞
2. RSVP [here](https://forms.gle/xYEKE8Bf8uTrosMs5)

**Comment by ashprakasan** [comment]
test poll

**Comment by ashprakasan** [comment]
Please vote :
Veg  🥔
Non-veg 🍤

**Comment by amitksingh1490** [comment]
RSVP is not working some permission issue. 😃
![image](https://user-images.githubusercontent.com/23661702/105985841-0e040b00-60c2-11eb-8059-635dbc7b331f.png)

**Comment by ashprakasan** [comment]
> RSVP is not working some permission issue. 😃
> ![image](https://user-images.githubusercontent.com/23661702/105985841-0e040b00-60c2-11eb-8059-635dbc7b331f.png)

Damn! Can you check now?

**Comment by krishna-kb** [comment]
#nitpicking
![image](https://user-images.githubusercontent.com/20321493/105986752-57a12580-60c3-11eb-88bd-ceb1fb17e648.png)
Are only married couples allowed at this party? 😂

**Comment by ashprakasan** [comment]
Looks like someone wants to bring their girlfriend 😄 
Otherwise, people just skip non-mandatory questions that don't apply to them.

**Comment by krishna-kb** [comment]
😂🤷🏻‍♂️ I was just nitpicking.
